
server:
    port: 8081
    error:
        include-stacktrace: never

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/A0016?&createDatabaseIfNotExist=true
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update